// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN4mZF8pb7N4zfv6z0Y1wHM3zzYfgffmE',
    appId: '1:968468854615:web:9db8f8b37e0414c7ca3012',
    messagingSenderId: '968468854615',
    projectId: 'covid-patient-84ea8',
    authDomain: 'covid-patient-84ea8.firebaseapp.com',
    storageBucket: 'covid-patient-84ea8.appspot.com',
    measurementId: 'G-86R5K485PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbqQ6DKEm__w_qd6g-5IPp_9Y6vlz0FOU',
    appId: '1:968468854615:android:5818d2c4dbd8c6c6ca3012',
    messagingSenderId: '968468854615',
    projectId: 'covid-patient-84ea8',
    storageBucket: 'covid-patient-84ea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMofyvEdvHdwxKt6nyPwJzJ0kfH1u8bw',
    appId: '1:968468854615:ios:393c7c1984f3adf3ca3012',
    messagingSenderId: '968468854615',
    projectId: 'covid-patient-84ea8',
    storageBucket: 'covid-patient-84ea8.appspot.com',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeMofyvEdvHdwxKt6nyPwJzJ0kfH1u8bw',
    appId: '1:968468854615:ios:393c7c1984f3adf3ca3012',
    messagingSenderId: '968468854615',
    projectId: 'covid-patient-84ea8',
    storageBucket: 'covid-patient-84ea8.appspot.com',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN4mZF8pb7N4zfv6z0Y1wHM3zzYfgffmE',
    appId: '1:968468854615:web:6c7bc193c8da0369ca3012',
    messagingSenderId: '968468854615',
    projectId: 'covid-patient-84ea8',
    authDomain: 'covid-patient-84ea8.firebaseapp.com',
    storageBucket: 'covid-patient-84ea8.appspot.com',
    measurementId: 'G-F3ZZR67XR7',
  );

}